/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as DailyPassRouteImport } from './routes/daily-pass'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PassRouteImport } from './routes/pass'
import { Route as RouteDashboardRouteImport } from './routes/route-dashboard'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TripsBalanceRouteImport } from './routes/trips-balance'
import { Route as WhatsappLiveRouteImport } from './routes/whatsapp-live'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCollectionsRouteImport } from './routes/admin/collections'
import { Route as AdminDailyPassesRouteImport } from './routes/admin/daily-passes'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminInstallmentsRouteImport } from './routes/admin/installments'
import { Route as AdminManifestsRouteImport } from './routes/admin/manifests'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminScanRouteImport } from './routes/admin/scan'
import { Route as AdminSchedulesRouteImport } from './routes/admin/schedules'
import { Route as AdminStudentAccountsRouteImport } from './routes/admin/student-accounts'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as GuestPassTokenRouteImport } from './routes/guest-pass/$token'
import { Route as SupervisorCollectionsRouteImport } from './routes/supervisor/collections'
import { Route as SupervisorStudentsRouteImport } from './routes/supervisor/students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPassRoute = DailyPassRouteImport.update({
  id: '/daily-pass',
  path: '/daily-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PassRoute = PassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteDashboardRoute = RouteDashboardRouteImport.update({
  id: '/route-dashboard',
  path: '/route-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsBalanceRoute = TripsBalanceRouteImport.update({
  id: '/trips-balance',
  path: '/trips-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappLiveRoute = WhatsappLiveRouteImport.update({
  id: '/whatsapp-live',
  path: '/whatsapp-live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDailyPassesRoute = AdminDailyPassesRouteImport.update({
  id: '/daily-passes',
  path: '/daily-passes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstallmentsRoute = AdminInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManifestsRoute = AdminManifestsRouteImport.update({
  id: '/manifests',
  path: '/manifests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScanRoute = AdminScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentAccountsRoute = AdminStudentAccountsRouteImport.update({
  id: '/student-accounts',
  path: '/student-accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const GuestPassTokenRoute = GuestPassTokenRouteImport.update({
  id: '/guest-pass/$token',
  path: '/guest-pass/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorCollectionsRoute = SupervisorCollectionsRouteImport.update({
  id: '/supervisor/collections',
  path: '/supervisor/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorStudentsRoute = SupervisorStudentsRouteImport.update({
  id: '/supervisor/students',
  path: '/supervisor/students',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/daily-pass': typeof DailyPassRoute
  '/dashboard': typeof DashboardRoute
  '/pass': typeof PassRoute
  '/route-dashboard': typeof RouteDashboardRoute
  '/trips': typeof TripsRoute
  '/trips-balance': typeof TripsBalanceRoute
  '/whatsapp-live': typeof WhatsappLiveRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/daily-passes': typeof AdminDailyPassesRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/manifests': typeof AdminManifestsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/student-accounts': typeof AdminStudentAccountsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/guest-pass/$token': typeof GuestPassTokenRoute
  '/supervisor/collections': typeof SupervisorCollectionsRoute
  '/supervisor/students': typeof SupervisorStudentsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/daily-pass': typeof DailyPassRoute
  '/dashboard': typeof DashboardRoute
  '/pass': typeof PassRoute
  '/route-dashboard': typeof RouteDashboardRoute
  '/trips': typeof TripsRoute
  '/trips-balance': typeof TripsBalanceRoute
  '/whatsapp-live': typeof WhatsappLiveRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/daily-passes': typeof AdminDailyPassesRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/manifests': typeof AdminManifestsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/student-accounts': typeof AdminStudentAccountsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/guest-pass/$token': typeof GuestPassTokenRoute
  '/supervisor/collections': typeof SupervisorCollectionsRoute
  '/supervisor/students': typeof SupervisorStudentsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/daily-pass': typeof DailyPassRoute
  '/dashboard': typeof DashboardRoute
  '/pass': typeof PassRoute
  '/route-dashboard': typeof RouteDashboardRoute
  '/trips': typeof TripsRoute
  '/trips-balance': typeof TripsBalanceRoute
  '/whatsapp-live': typeof WhatsappLiveRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/daily-passes': typeof AdminDailyPassesRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/manifests': typeof AdminManifestsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/student-accounts': typeof AdminStudentAccountsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/guest-pass/$token': typeof GuestPassTokenRoute
  '/supervisor/collections': typeof SupervisorCollectionsRoute
  '/supervisor/students': typeof SupervisorStudentsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/daily-pass'
    | '/dashboard'
    | '/pass'
    | '/route-dashboard'
    | '/trips'
    | '/trips-balance'
    | '/whatsapp-live'
    | '/admin/collections'
    | '/admin/daily-passes'
    | '/admin/import'
    | '/admin/installments'
    | '/admin/manifests'
    | '/admin/requests'
    | '/admin/scan'
    | '/admin/schedules'
    | '/admin/student-accounts'
    | '/admin/students'
    | '/admin/users'
    | '/guest-pass/$token'
    | '/supervisor/collections'
    | '/supervisor/students'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/daily-pass'
    | '/dashboard'
    | '/pass'
    | '/route-dashboard'
    | '/trips'
    | '/trips-balance'
    | '/whatsapp-live'
    | '/admin/collections'
    | '/admin/daily-passes'
    | '/admin/import'
    | '/admin/installments'
    | '/admin/manifests'
    | '/admin/requests'
    | '/admin/scan'
    | '/admin/schedules'
    | '/admin/student-accounts'
    | '/admin/students'
    | '/admin/users'
    | '/guest-pass/$token'
    | '/supervisor/collections'
    | '/supervisor/students'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/daily-pass'
    | '/dashboard'
    | '/pass'
    | '/route-dashboard'
    | '/trips'
    | '/trips-balance'
    | '/whatsapp-live'
    | '/admin/collections'
    | '/admin/daily-passes'
    | '/admin/import'
    | '/admin/installments'
    | '/admin/manifests'
    | '/admin/requests'
    | '/admin/scan'
    | '/admin/schedules'
    | '/admin/student-accounts'
    | '/admin/students'
    | '/admin/users'
    | '/guest-pass/$token'
    | '/supervisor/collections'
    | '/supervisor/students'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DailyPassRoute: typeof DailyPassRoute
  DashboardRoute: typeof DashboardRoute
  PassRoute: typeof PassRoute
  RouteDashboardRoute: typeof RouteDashboardRoute
  TripsRoute: typeof TripsRoute
  TripsBalanceRoute: typeof TripsBalanceRoute
  WhatsappLiveRoute: typeof WhatsappLiveRoute
  GuestPassTokenRoute: typeof GuestPassTokenRoute
  SupervisorCollectionsRoute: typeof SupervisorCollectionsRoute
  SupervisorStudentsRoute: typeof SupervisorStudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-pass': {
      id: '/daily-pass'
      path: '/daily-pass'
      fullPath: '/daily-pass'
      preLoaderRoute: typeof DailyPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-dashboard': {
      id: '/route-dashboard'
      path: '/route-dashboard'
      fullPath: '/route-dashboard'
      preLoaderRoute: typeof RouteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips-balance': {
      id: '/trips-balance'
      path: '/trips-balance'
      fullPath: '/trips-balance'
      preLoaderRoute: typeof TripsBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-live': {
      id: '/whatsapp-live'
      path: '/whatsapp-live'
      fullPath: '/whatsapp-live'
      preLoaderRoute: typeof WhatsappLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/daily-passes': {
      id: '/admin/daily-passes'
      path: '/daily-passes'
      fullPath: '/admin/daily-passes'
      preLoaderRoute: typeof AdminDailyPassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/installments': {
      id: '/admin/installments'
      path: '/installments'
      fullPath: '/admin/installments'
      preLoaderRoute: typeof AdminInstallmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manifests': {
      id: '/admin/manifests'
      path: '/manifests'
      fullPath: '/admin/manifests'
      preLoaderRoute: typeof AdminManifestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scan': {
      id: '/admin/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AdminScanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/student-accounts': {
      id: '/admin/student-accounts'
      path: '/student-accounts'
      fullPath: '/admin/student-accounts'
      preLoaderRoute: typeof AdminStudentAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/guest-pass/$token': {
      id: '/guest-pass/$token'
      path: '/guest-pass/$token'
      fullPath: '/guest-pass/$token'
      preLoaderRoute: typeof GuestPassTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/collections': {
      id: '/supervisor/collections'
      path: '/supervisor/collections'
      fullPath: '/supervisor/collections'
      preLoaderRoute: typeof SupervisorCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/students': {
      id: '/supervisor/students'
      path: '/supervisor/students'
      fullPath: '/supervisor/students'
      preLoaderRoute: typeof SupervisorStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminDailyPassesRoute: typeof AdminDailyPassesRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminInstallmentsRoute: typeof AdminInstallmentsRoute
  AdminManifestsRoute: typeof AdminManifestsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminScanRoute: typeof AdminScanRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminStudentAccountsRoute: typeof AdminStudentAccountsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminDailyPassesRoute: AdminDailyPassesRoute,
  AdminImportRoute: AdminImportRoute,
  AdminInstallmentsRoute: AdminInstallmentsRoute,
  AdminManifestsRoute: AdminManifestsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminScanRoute: AdminScanRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminStudentAccountsRoute: AdminStudentAccountsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DailyPassRoute: DailyPassRoute,
  DashboardRoute: DashboardRoute,
  PassRoute: PassRoute,
  RouteDashboardRoute: RouteDashboardRoute,
  TripsRoute: TripsRoute,
  TripsBalanceRoute: TripsBalanceRoute,
  WhatsappLiveRoute: WhatsappLiveRoute,
  GuestPassTokenRoute: GuestPassTokenRoute,
  SupervisorCollectionsRoute: SupervisorCollectionsRoute,
  SupervisorStudentsRoute: SupervisorStudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
