/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DailyPassRouteImport } from './routes/daily-pass'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PassRouteImport } from './routes/pass'
import { Route as AdminInstallmentsRouteImport } from './routes/admin/installments'
import { Route as GuestPassTokenRouteImport } from './routes/guest-pass/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPassRoute = DailyPassRouteImport.update({
  id: '/daily-pass',
  path: '/daily-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PassRoute = PassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstallmentsRoute = AdminInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AdminRoute,
} as any)
const GuestPassTokenRoute = GuestPassTokenRouteImport.update({
  id: '/guest-pass/$token',
  path: '/guest-pass/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/daily-pass': typeof DailyPassRoute
  '/dashboard': typeof DashboardRoute
  '/pass': typeof PassRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/guest-pass/$token': typeof GuestPassTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/daily-pass': typeof DailyPassRoute
  '/dashboard': typeof DashboardRoute
  '/pass': typeof PassRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/guest-pass/$token': typeof GuestPassTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/daily-pass': typeof DailyPassRoute
  '/dashboard': typeof DashboardRoute
  '/pass': typeof PassRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/guest-pass/$token': typeof GuestPassTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/daily-pass'
    | '/dashboard'
    | '/pass'
    | '/admin/installments'
    | '/guest-pass/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/daily-pass'
    | '/dashboard'
    | '/pass'
    | '/admin/installments'
    | '/guest-pass/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/daily-pass'
    | '/dashboard'
    | '/pass'
    | '/admin/installments'
    | '/guest-pass/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DailyPassRoute: typeof DailyPassRoute
  DashboardRoute: typeof DashboardRoute
  PassRoute: typeof PassRoute
  GuestPassTokenRoute: typeof GuestPassTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-pass': {
      id: '/daily-pass'
      path: '/daily-pass'
      fullPath: '/daily-pass'
      preLoaderRoute: typeof DailyPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/installments': {
      id: '/admin/installments'
      path: '/installments'
      fullPath: '/admin/installments'
      preLoaderRoute: typeof AdminInstallmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/guest-pass/$token': {
      id: '/guest-pass/$token'
      path: '/guest-pass/$token'
      fullPath: '/guest-pass/$token'
      preLoaderRoute: typeof GuestPassTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminInstallmentsRoute: typeof AdminInstallmentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInstallmentsRoute: AdminInstallmentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DailyPassRoute: DailyPassRoute,
  DashboardRoute: DashboardRoute,
  PassRoute: PassRoute,
  GuestPassTokenRoute: GuestPassTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
