-- One-off backfill: correct pickup_stop for students already imported
-- before the route-column stop-extraction fix. Matches by normalized
-- phone number (comparing only digits), same as the bulk-import upsert.

update public.profiles set pickup_stop = 'اسكوت' where regexp_replace(phone, '\D', '', 'g') = '01222421726';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01203798621';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '01204032281';
update public.profiles set pickup_stop = 'اخر سور نادي سبورتنج' where regexp_replace(phone, '\D', '', 'g') = '01068707565';
update public.profiles set pickup_stop = 'ليزابيلا' where regexp_replace(phone, '\D', '', 'g') = '01211174492';
update public.profiles set pickup_stop = 'فضة' where regexp_replace(phone, '\D', '', 'g') = '01111238952';
update public.profiles set pickup_stop = 'إشارة The Walk' where regexp_replace(phone, '\D', '', 'g') = '01091979598';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01206046979';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01064105665';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01023956099';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01000325953';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01550521473';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '01002183385';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01550852077';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01221016813';
update public.profiles set pickup_stop = 'حسني' where regexp_replace(phone, '\D', '', 'g') = '01211280874';
update public.profiles set pickup_stop = 'كرم الشام' where regexp_replace(phone, '\D', '', 'g') = '01271940548';
update public.profiles set pickup_stop = 'المندرة' where regexp_replace(phone, '\D', '', 'g') = '01225852965';
update public.profiles set pickup_stop = 'وي الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01202312202';
update public.profiles set pickup_stop = 'حديد وصلب' where regexp_replace(phone, '\D', '', 'g') = '01208336681';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01553431677';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01098572610';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01202291010';
update public.profiles set pickup_stop = 'مصطفى كامل' where regexp_replace(phone, '\D', '', 'g') = '01278424643';
update public.profiles set pickup_stop = 'حسني' where regexp_replace(phone, '\D', '', 'g') = '01280294009';
update public.profiles set pickup_stop = 'حديد وصلب' where regexp_replace(phone, '\D', '', 'g') = '01203395132';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01271883225';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01029018607';
update public.profiles set pickup_stop = 'الشاطبي' where regexp_replace(phone, '\D', '', 'g') = '01008903954';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01068681491';
update public.profiles set pickup_stop = 'الاقبال' where regexp_replace(phone, '\D', '', 'g') = '01101855360';
update public.profiles set pickup_stop = 'منصور شيفروليه' where regexp_replace(phone, '\D', '', 'g') = '01099403896';
update public.profiles set pickup_stop = 'كوبري سكينة' where regexp_replace(phone, '\D', '', 'g') = '01115313112';
update public.profiles set pickup_stop = 'الشبان المسلمين' where regexp_replace(phone, '\D', '', 'g') = '01224557764';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '01273380071';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01276519948';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01011381591';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01203968642';
update public.profiles set pickup_stop = 'كرموز' where regexp_replace(phone, '\D', '', 'g') = '01279142850';
update public.profiles set pickup_stop = 'عبد الحليم' where regexp_replace(phone, '\D', '', 'g') = '01000238411';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01019165860';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01289816335';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01201011669';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01115407634';
update public.profiles set pickup_stop = 'كومباوند الفيروزة' where regexp_replace(phone, '\D', '', 'g') = '1276687929';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01204388097';
update public.profiles set pickup_stop = 'كنيسة جناكليس' where regexp_replace(phone, '\D', '', 'g') = '01279603313';
update public.profiles set pickup_stop = 'حديد وصلب' where regexp_replace(phone, '\D', '', 'g') = '01200412101';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01030299142';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01282522721';
update public.profiles set pickup_stop = 'حسني' where regexp_replace(phone, '\D', '', 'g') = '01287163284';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01201162442';
update public.profiles set pickup_stop = 'كرم الشام' where regexp_replace(phone, '\D', '', 'g') = '01151644301';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01200911721';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01126165677';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '1553812281';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01501098801';
update public.profiles set pickup_stop = 'سيدي جابر' where regexp_replace(phone, '\D', '', 'g') = '01233397431';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01200555301';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01120229942';
update public.profiles set pickup_stop = 'بنزينة قسم الرمل' where regexp_replace(phone, '\D', '', 'g') = '01019928620';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01550341484';
update public.profiles set pickup_stop = 'بنزينة قسم الرمل' where regexp_replace(phone, '\D', '', 'g') = '01283890996';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01093337492';
update public.profiles set pickup_stop = 'كيلوبترا' where regexp_replace(phone, '\D', '', 'g') = '01064984920';
update public.profiles set pickup_stop = 'العزيزية' where regexp_replace(phone, '\D', '', 'g') = '01201020383';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01202987890';
update public.profiles set pickup_stop = 'كيلوبترا' where regexp_replace(phone, '\D', '', 'g') = '01559148502';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01127817192';
update public.profiles set pickup_stop = 'ابو يوسف' where regexp_replace(phone, '\D', '', 'g') = '01208825722';
update public.profiles set pickup_stop = 'كارفور القهوة' where regexp_replace(phone, '\D', '', 'g') = '01272910392';
update public.profiles set pickup_stop = 'نفق ٤٥' where regexp_replace(phone, '\D', '', 'g') = '201024037837';
update public.profiles set pickup_stop = 'اشارة كارفور' where regexp_replace(phone, '\D', '', 'g') = '01226404259';
update public.profiles set pickup_stop = 'ليزابيلا' where regexp_replace(phone, '\D', '', 'g') = '01096619234';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01019174261';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01065033657';
update public.profiles set pickup_stop = 'كومباوند الفيروزة' where regexp_replace(phone, '\D', '', 'g') = '01010299989';
update public.profiles set pickup_stop = 'ابو يوسف' where regexp_replace(phone, '\D', '', 'g') = '01202583404';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01204493441';
update public.profiles set pickup_stop = 'المدهش' where regexp_replace(phone, '\D', '', 'g') = '01032928877';
update public.profiles set pickup_stop = 'البيضة' where regexp_replace(phone, '\D', '', 'g') = '01281510167';
update public.profiles set pickup_stop = 'الشيراتون' where regexp_replace(phone, '\D', '', 'g') = '01095650057';
update public.profiles set pickup_stop = 'اشارة كارفور' where regexp_replace(phone, '\D', '', 'g') = '01220460456';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01143777623';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '1212723044';
update public.profiles set pickup_stop = 'سبورتينج' where regexp_replace(phone, '\D', '', 'g') = '01556824012';
update public.profiles set pickup_stop = 'الشبان المسلمين' where regexp_replace(phone, '\D', '', 'g') = '01277629577';
update public.profiles set pickup_stop = 'سيدي جابر' where regexp_replace(phone, '\D', '', 'g') = '01065004855';
update public.profiles set pickup_stop = 'اول العوايد' where regexp_replace(phone, '\D', '', 'g') = '1202750678';
update public.profiles set pickup_stop = 'بيتزا دادي' where regexp_replace(phone, '\D', '', 'g') = '01124141685';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01091764590';
update public.profiles set pickup_stop = 'كنيسة جناكليس' where regexp_replace(phone, '\D', '', 'g') = '01222667424';
update public.profiles set pickup_stop = 'كومباوند الفيروزة' where regexp_replace(phone, '\D', '', 'g') = '01281415712';
update public.profiles set pickup_stop = 'عبد الحليم' where regexp_replace(phone, '\D', '', 'g') = '01210864368';
update public.profiles set pickup_stop = 'بنزينة كليوباترا' where regexp_replace(phone, '\D', '', 'g') = '01271482202';
update public.profiles set pickup_stop = 'النموذجية' where regexp_replace(phone, '\D', '', 'g') = '01207323995';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01227446633';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01200023729';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01554520076';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01011155266';
update public.profiles set pickup_stop = 'حديد وصلب' where regexp_replace(phone, '\D', '', 'g') = '01222446676';
update public.profiles set pickup_stop = 'سانتوس' where regexp_replace(phone, '\D', '', 'g') = '01222358694';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01149126396';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01276538041';
update public.profiles set pickup_stop = 'الشيراتون' where regexp_replace(phone, '\D', '', 'g') = '01008111237';
update public.profiles set pickup_stop = 'بنزينة جليم' where regexp_replace(phone, '\D', '', 'g') = '01123190195';
update public.profiles set pickup_stop = 'شارع الحدايق' where regexp_replace(phone, '\D', '', 'g') = '01223550054';
update public.profiles set pickup_stop = 'المدخل' where regexp_replace(phone, '\D', '', 'g') = '01000426159';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01288010681';
update public.profiles set pickup_stop = 'النموذجية' where regexp_replace(phone, '\D', '', 'g') = '01120190270';
update public.profiles set pickup_stop = 'النموذجية' where regexp_replace(phone, '\D', '', 'g') = '01201239315';
update public.profiles set pickup_stop = 'اشارة كارفور' where regexp_replace(phone, '\D', '', 'g') = '01285939888';
update public.profiles set pickup_stop = 'الحضرة' where regexp_replace(phone, '\D', '', 'g') = '01227092199';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01050479229';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01127170008';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01090540037';
update public.profiles set pickup_stop = 'ليزابيلا' where regexp_replace(phone, '\D', '', 'g') = '01227649082';
update public.profiles set pickup_stop = 'اخر ابيس' where regexp_replace(phone, '\D', '', 'g') = '01125225474';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01112998944';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01092300218';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01201395393';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01025325954';
update public.profiles set pickup_stop = 'العوايد' where regexp_replace(phone, '\D', '', 'g') = '01069860889';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01557502077';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01276282646';
update public.profiles set pickup_stop = 'بنزينة جليم' where regexp_replace(phone, '\D', '', 'g') = '01000808079';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01287510445';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01010999319';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01223415768';
update public.profiles set pickup_stop = 'النموذجية' where regexp_replace(phone, '\D', '', 'g') = '01207971813';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01003449639';
update public.profiles set pickup_stop = 'سيدي جابر' where regexp_replace(phone, '\D', '', 'g') = '01208715137';
update public.profiles set pickup_stop = 'كنيسة جناكليس' where regexp_replace(phone, '\D', '', 'g') = '01123652986';
update public.profiles set pickup_stop = 'خليل حمادة' where regexp_replace(phone, '\D', '', 'g') = '01006025296';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01067683097';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01068669221';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01272885503';
update public.profiles set pickup_stop = 'المعموره ش٢٥' where regexp_replace(phone, '\D', '', 'g') = '01220559543';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01092390115';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01064399753';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01095699851';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01062215563';
update public.profiles set pickup_stop = 'بنزينة جليم' where regexp_replace(phone, '\D', '', 'g') = '01207832867';
update public.profiles set pickup_stop = 'اسكوت' where regexp_replace(phone, '\D', '', 'g') = '01515868735';
update public.profiles set pickup_stop = 'اسكوت' where regexp_replace(phone, '\D', '', 'g') = '01201184412';
update public.profiles set pickup_stop = 'خليل حمادة' where regexp_replace(phone, '\D', '', 'g') = '01204518196';
update public.profiles set pickup_stop = 'الموقف' where regexp_replace(phone, '\D', '', 'g') = '01280269223';
update public.profiles set pickup_stop = 'اخر سور نادي سبورتنج' where regexp_replace(phone, '\D', '', 'g') = '01032486449';
update public.profiles set pickup_stop = 'بيتزا دادي' where regexp_replace(phone, '\D', '', 'g') = '01552020777';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01208393048';
update public.profiles set pickup_stop = 'الشيراتون' where regexp_replace(phone, '\D', '', 'g') = '01203967773';
update public.profiles set pickup_stop = 'بنزينة قسم الرمل' where regexp_replace(phone, '\D', '', 'g') = '01554611135';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01124163316';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01271150352';
update public.profiles set pickup_stop = 'كابو' where regexp_replace(phone, '\D', '', 'g') = '01210595700';
update public.profiles set pickup_stop = 'النموذجية' where regexp_replace(phone, '\D', '', 'g') = '01023388454';
update public.profiles set pickup_stop = 'ساحل' where regexp_replace(phone, '\D', '', 'g') = '01080428877';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01201733364';
update public.profiles set pickup_stop = 'ساحل' where regexp_replace(phone, '\D', '', 'g') = '01069144455';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01274669278';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01273757602';
update public.profiles set pickup_stop = 'العزيزية' where regexp_replace(phone, '\D', '', 'g') = '01157581813';
update public.profiles set pickup_stop = 'سان ستيفانو' where regexp_replace(phone, '\D', '', 'g') = '01550372910';
update public.profiles set pickup_stop = 'النجار' where regexp_replace(phone, '\D', '', 'g') = '01206464619';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01555122389';
update public.profiles set pickup_stop = 'نفق ٤٥' where regexp_replace(phone, '\D', '', 'g') = '01281215658';
update public.profiles set pickup_stop = 'الشاطبي' where regexp_replace(phone, '\D', '', 'g') = '01050912935';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01012968927';
update public.profiles set pickup_stop = 'اول العوايد' where regexp_replace(phone, '\D', '', 'g') = '01284299228';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01281159761';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01271734680';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01202048003';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01203943345';
update public.profiles set pickup_stop = 'الشيراتون' where regexp_replace(phone, '\D', '', 'g') = '01229658350';
update public.profiles set pickup_stop = 'خليل حمادة' where regexp_replace(phone, '\D', '', 'g') = '01095981781';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01151635396';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01228377458';
update public.profiles set pickup_stop = 'بنزينة كيلوباترا' where regexp_replace(phone, '\D', '', 'g') = '01014413077';
update public.profiles set pickup_stop = 'كيلوبترا' where regexp_replace(phone, '\D', '', 'g') = '01277496303';
update public.profiles set pickup_stop = 'الشركة العربية' where regexp_replace(phone, '\D', '', 'g') = '01552085768';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01226433972';
update public.profiles set pickup_stop = 'النموذجية' where regexp_replace(phone, '\D', '', 'g') = '01203965041';
update public.profiles set pickup_stop = 'المنتزة' where regexp_replace(phone, '\D', '', 'g') = '01270869663';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01201807126';
update public.profiles set pickup_stop = 'اخر ابيس' where regexp_replace(phone, '\D', '', 'g') = '01270838834';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01029018607';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01125061717';
update public.profiles set pickup_stop = 'شارع الحدايق' where regexp_replace(phone, '\D', '', 'g') = '01062840843';
update public.profiles set pickup_stop = 'شارع الترعة' where regexp_replace(phone, '\D', '', 'g') = '01016923876';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01207654764';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01299920968';
update public.profiles set pickup_stop = 'بيتزا دادي' where regexp_replace(phone, '\D', '', 'g') = '01273562312';
update public.profiles set pickup_stop = 'وي الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01221417759';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01228688033';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01200037215';
update public.profiles set pickup_stop = 'الإبراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01270047004';
update public.profiles set pickup_stop = 'النموذجية' where regexp_replace(phone, '\D', '', 'g') = '01551119976';
update public.profiles set pickup_stop = 'سبورتينج' where regexp_replace(phone, '\D', '', 'g') = '01200170114';
update public.profiles set pickup_stop = 'ادفينا' where regexp_replace(phone, '\D', '', 'g') = '01042589170';
update public.profiles set pickup_stop = 'الشرطة العسكرية' where regexp_replace(phone, '\D', '', 'g') = '01285640566';
update public.profiles set pickup_stop = 'كارفور القهوة' where regexp_replace(phone, '\D', '', 'g') = '01284288338';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01007180307';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01127422553';
update public.profiles set pickup_stop = 'النموذجية' where regexp_replace(phone, '\D', '', 'g') = '1050475344';
update public.profiles set pickup_stop = 'النموذجية' where regexp_replace(phone, '\D', '', 'g') = '01280889915';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01222149873';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01200624724';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01018876444';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01272887396';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01508520121';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01204097866';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01070230802';
update public.profiles set pickup_stop = 'نفق ٤٥' where regexp_replace(phone, '\D', '', 'g') = '01014199801';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01205642323';
update public.profiles set pickup_stop = 'الإبراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01283551587';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01507827109';
update public.profiles set pickup_stop = 'شارع الترعة' where regexp_replace(phone, '\D', '', 'g') = '01040254475';
update public.profiles set pickup_stop = 'خورشيد' where regexp_replace(phone, '\D', '', 'g') = '01203095850';
update public.profiles set pickup_stop = 'خورشيد' where regexp_replace(phone, '\D', '', 'g') = '01221576414';
update public.profiles set pickup_stop = 'الإبراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01111200638';
update public.profiles set pickup_stop = 'خليل حمادة' where regexp_replace(phone, '\D', '', 'g') = '01060102779';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01200361941';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01093527279';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01204765405';
update public.profiles set pickup_stop = 'كارفور القهوة' where regexp_replace(phone, '\D', '', 'g') = '01097177027';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01099377883';
update public.profiles set pickup_stop = 'الحضرة' where regexp_replace(phone, '\D', '', 'g') = '01228144710';
update public.profiles set pickup_stop = 'كارفور القهوة' where regexp_replace(phone, '\D', '', 'g') = '01201638419';
update public.profiles set pickup_stop = 'المدهش' where regexp_replace(phone, '\D', '', 'g') = '01032156317';
update public.profiles set pickup_stop = 'سيدي بشر' where regexp_replace(phone, '\D', '', 'g') = '01210106164';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01014691725';
update public.profiles set pickup_stop = 'النجار' where regexp_replace(phone, '\D', '', 'g') = '01007283704';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01092315152';
update public.profiles set pickup_stop = 'سيدي بشر' where regexp_replace(phone, '\D', '', 'g') = '01210106461';
update public.profiles set pickup_stop = 'المعموره ش٢٥' where regexp_replace(phone, '\D', '', 'g') = '01156622273';
update public.profiles set pickup_stop = 'كومباوند الفيروزة' where regexp_replace(phone, '\D', '', 'g') = '01128935398';
update public.profiles set pickup_stop = 'ابو يوسف' where regexp_replace(phone, '\D', '', 'g') = '01014457036';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01270711159';
update public.profiles set pickup_stop = 'ادفينا' where regexp_replace(phone, '\D', '', 'g') = '01220822603';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01203933868';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01224926451';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01205036935';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '01097800288';
update public.profiles set pickup_stop = 'وي الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01012278698';
update public.profiles set pickup_stop = 'الاقبال' where regexp_replace(phone, '\D', '', 'g') = '01041090967';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01205800068';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01018143103';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '1208909021';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01284111962';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01090970973';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01270331266';
update public.profiles set pickup_stop = 'المنتزة' where regexp_replace(phone, '\D', '', 'g') = '01515471678';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01000074255';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01271757188';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01221658315';
update public.profiles set pickup_stop = 'بنزينة جليم' where regexp_replace(phone, '\D', '', 'g') = '01027475160';
update public.profiles set pickup_stop = 'الشرطة العسكرية' where regexp_replace(phone, '\D', '', 'g') = '01068305937';
update public.profiles set pickup_stop = 'اطلس' where regexp_replace(phone, '\D', '', 'g') = '01551370563';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '1011262191';
update public.profiles set pickup_stop = 'العزيزية' where regexp_replace(phone, '\D', '', 'g') = '01226050984';
update public.profiles set pickup_stop = 'كرموز' where regexp_replace(phone, '\D', '', 'g') = '01202056420';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01022214214';
update public.profiles set pickup_stop = 'كيلوبترا' where regexp_replace(phone, '\D', '', 'g') = '01002710897';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01202979834';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01013621346';
update public.profiles set pickup_stop = 'كوبري سكينة' where regexp_replace(phone, '\D', '', 'g') = '01207639133';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '1514191629';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01284158392';
update public.profiles set pickup_stop = 'بنزينة قسم الرمل' where regexp_replace(phone, '\D', '', 'g') = '01281392571';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01274163699';
update public.profiles set pickup_stop = 'صحراوي' where regexp_replace(phone, '\D', '', 'g') = '01226268421';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01062042593';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01272969602';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01207716299';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01557881914';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01551191093';
update public.profiles set pickup_stop = 'الإبراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01505601998';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01225392726';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01212057142';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01553011775';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01270567500';
update public.profiles set pickup_stop = 'شارع الترعة' where regexp_replace(phone, '\D', '', 'g') = '01203507588';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01099935685';
update public.profiles set pickup_stop = 'بيتزا دادي' where regexp_replace(phone, '\D', '', 'g') = '01069604543';
update public.profiles set pickup_stop = 'بنزينة كليوباترا' where regexp_replace(phone, '\D', '', 'g') = '01003968801';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01055210778';
update public.profiles set pickup_stop = 'كرم الشام' where regexp_replace(phone, '\D', '', 'g') = '01229608421';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01065235590';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01274383709';
update public.profiles set pickup_stop = 'كامب شيزار' where regexp_replace(phone, '\D', '', 'g') = '01093702042';
update public.profiles set pickup_stop = 'بنزينة قسم الرمل' where regexp_replace(phone, '\D', '', 'g') = '01225672998';
update public.profiles set pickup_stop = 'بنزينة قسم الرمل' where regexp_replace(phone, '\D', '', 'g') = '01225673034';
update public.profiles set pickup_stop = 'خورشيد' where regexp_replace(phone, '\D', '', 'g') = '01280671291';
update public.profiles set pickup_stop = 'النجار' where regexp_replace(phone, '\D', '', 'g') = '01283443497';
update public.profiles set pickup_stop = 'كامب شيزار' where regexp_replace(phone, '\D', '', 'g') = '01093702042';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01092390115';
update public.profiles set pickup_stop = 'خورشيد' where regexp_replace(phone, '\D', '', 'g') = '01274819546';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01028499958';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01550339108';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01021518869';
update public.profiles set pickup_stop = 'بنزينة كليوباترا' where regexp_replace(phone, '\D', '', 'g') = '01224097669';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01118256577';
update public.profiles set pickup_stop = 'شارع سوريا' where regexp_replace(phone, '\D', '', 'g') = '01210701520';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01554935564';
update public.profiles set pickup_stop = 'بنزينة جليم' where regexp_replace(phone, '\D', '', 'g') = '01223715509';
update public.profiles set pickup_stop = 'اخر سور نادي سبورتنج' where regexp_replace(phone, '\D', '', 'g') = '01286446610';
update public.profiles set pickup_stop = 'عبد الحليم' where regexp_replace(phone, '\D', '', 'g') = '01146571113';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01200751116';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01096120454';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01001026062';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01280170234';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01114709929';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01019180459';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01282934814';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01282936972';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01282936972';
update public.profiles set pickup_stop = 'المدهش' where regexp_replace(phone, '\D', '', 'g') = '01145873908';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01060039316';
update public.profiles set pickup_stop = 'ليزابيلا' where regexp_replace(phone, '\D', '', 'g') = '01281711780';
update public.profiles set pickup_stop = 'ليزابيلا' where regexp_replace(phone, '\D', '', 'g') = '01281711780';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01021917558';
update public.profiles set pickup_stop = 'بنزينة كليوباترا' where regexp_replace(phone, '\D', '', 'g') = '01200532331';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01030973785';
update public.profiles set pickup_stop = 'كوبري الناموس' where regexp_replace(phone, '\D', '', 'g') = '01220855882';
update public.profiles set pickup_stop = 'كارفور القهوة' where regexp_replace(phone, '\D', '', 'g') = '01552497079';
update public.profiles set pickup_stop = 'وي الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01144529087';
update public.profiles set pickup_stop = 'اشارة هندسة' where regexp_replace(phone, '\D', '', 'g') = '01004992804';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01557722051';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01225636720';
update public.profiles set pickup_stop = 'القسم' where regexp_replace(phone, '\D', '', 'g') = '01025422690';
update public.profiles set pickup_stop = 'الشيراتون' where regexp_replace(phone, '\D', '', 'g') = '01155524719';
update public.profiles set pickup_stop = 'الشيراتون' where regexp_replace(phone, '\D', '', 'g') = '01094353316';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01202347520';
update public.profiles set pickup_stop = 'كابو' where regexp_replace(phone, '\D', '', 'g') = '01223581985';
update public.profiles set pickup_stop = 'الشركة العربية' where regexp_replace(phone, '\D', '', 'g') = '01098154861';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01204191304';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01227422382';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01229723550';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '1120067041';
update public.profiles set pickup_stop = 'ادفينا' where regexp_replace(phone, '\D', '', 'g') = '01094948320';
update public.profiles set pickup_stop = 'منصور شيفروليه' where regexp_replace(phone, '\D', '', 'g') = '01211797945';
update public.profiles set pickup_stop = 'الشاطبي' where regexp_replace(phone, '\D', '', 'g') = '01208006647';
update public.profiles set pickup_stop = 'الديب مول' where regexp_replace(phone, '\D', '', 'g') = '01101252735';
update public.profiles set pickup_stop = 'مصطفى كامل' where regexp_replace(phone, '\D', '', 'g') = '01010933400';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01558187085';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01273324948';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01112006887';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01155261337';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01202085763';
update public.profiles set pickup_stop = 'اخر ابيس' where regexp_replace(phone, '\D', '', 'g') = '01286533991';
update public.profiles set pickup_stop = 'شارع المحكمة' where regexp_replace(phone, '\D', '', 'g') = '01551039306';
update public.profiles set pickup_stop = 'المدخل' where regexp_replace(phone, '\D', '', 'g') = '01024665460';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01211177238';
update public.profiles set pickup_stop = 'كيلوبترا' where regexp_replace(phone, '\D', '', 'g') = '01019311498';
update public.profiles set pickup_stop = 'المدخل' where regexp_replace(phone, '\D', '', 'g') = '01002298341';
update public.profiles set pickup_stop = '26 يوليو' where regexp_replace(phone, '\D', '', 'g') = '01123061238';
update public.profiles set pickup_stop = 'الديب مول' where regexp_replace(phone, '\D', '', 'g') = '01069633942';
update public.profiles set pickup_stop = 'العزيزية' where regexp_replace(phone, '\D', '', 'g') = '01201101553';
update public.profiles set pickup_stop = 'المعموره ش٢٥' where regexp_replace(phone, '\D', '', 'g') = '01027101093';
update public.profiles set pickup_stop = 'شارع الحدايق' where regexp_replace(phone, '\D', '', 'g') = '01050334857';
update public.profiles set pickup_stop = 'حديد وصلب' where regexp_replace(phone, '\D', '', 'g') = '01210242161';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01277744525';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '01096891801';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01200032375';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01206339742';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01005700789';
update public.profiles set pickup_stop = 'بنزينة كليوباترا' where regexp_replace(phone, '\D', '', 'g') = '01229814270';
update public.profiles set pickup_stop = 'ابو يوسف' where regexp_replace(phone, '\D', '', 'g') = '01227492817';
update public.profiles set pickup_stop = 'عبد الحليم' where regexp_replace(phone, '\D', '', 'g') = '01555931614';
update public.profiles set pickup_stop = 'النجار' where regexp_replace(phone, '\D', '', 'g') = '01275475215';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01070642260';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01287188804';
update public.profiles set pickup_stop = 'المدخل' where regexp_replace(phone, '\D', '', 'g') = '01212949253';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01551492298';
update public.profiles set pickup_stop = 'كنيسة جناكليس' where regexp_replace(phone, '\D', '', 'g') = '01273921429';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01212977773';
update public.profiles set pickup_stop = 'الديب مول' where regexp_replace(phone, '\D', '', 'g') = '01029925690';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01155582116';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01288800121';
update public.profiles set pickup_stop = 'اخر ابيس' where regexp_replace(phone, '\D', '', 'g') = '01228393756';
update public.profiles set pickup_stop = 'سانتوس' where regexp_replace(phone, '\D', '', 'g') = '01066174412';
update public.profiles set pickup_stop = 'بنزينة جليم' where regexp_replace(phone, '\D', '', 'g') = '01272946601';
update public.profiles set pickup_stop = 'كومباوند الفيروزة' where regexp_replace(phone, '\D', '', 'g') = '01208076395';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01550340827';
update public.profiles set pickup_stop = 'المنتزة' where regexp_replace(phone, '\D', '', 'g') = '01205503814';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01092955248';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01278800762';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '01024702096';
update public.profiles set pickup_stop = 'ابو يوسف' where regexp_replace(phone, '\D', '', 'g') = '01019509769';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '01203257711';
update public.profiles set pickup_stop = 'الشيراتون' where regexp_replace(phone, '\D', '', 'g') = '01004839125';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01025807548';
update public.profiles set pickup_stop = 'اخر ابيس' where regexp_replace(phone, '\D', '', 'g') = '01200075643';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01271704070';
update public.profiles set pickup_stop = 'سيدي جابر' where regexp_replace(phone, '\D', '', 'g') = '01272229532';
update public.profiles set pickup_stop = 'سيدي جابر' where regexp_replace(phone, '\D', '', 'g') = '01103004821';
update public.profiles set pickup_stop = 'سيدي جابر' where regexp_replace(phone, '\D', '', 'g') = '01003244965';
update public.profiles set pickup_stop = 'سانتوس' where regexp_replace(phone, '\D', '', 'g') = '01206649550';
update public.profiles set pickup_stop = 'جامع يحيى' where regexp_replace(phone, '\D', '', 'g') = '01211184498';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01279606425';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01279606542';
update public.profiles set pickup_stop = 'اخر ابيس' where regexp_replace(phone, '\D', '', 'g') = '01112235182';
update public.profiles set pickup_stop = 'سان ستيفانو' where regexp_replace(phone, '\D', '', 'g') = '01273473999';
update public.profiles set pickup_stop = 'منصور شيفروليه' where regexp_replace(phone, '\D', '', 'g') = '01212840173';
update public.profiles set pickup_stop = 'جامع يحيى' where regexp_replace(phone, '\D', '', 'g') = '01212233692';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '01223494950';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01000341529';
update public.profiles set pickup_stop = 'كنيسة جناكليس' where regexp_replace(phone, '\D', '', 'g') = '01121071633';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01229038855';
update public.profiles set pickup_stop = 'كرم الشام' where regexp_replace(phone, '\D', '', 'g') = '01096935429';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01210606001';
update public.profiles set pickup_stop = 'مصطفى كامل' where regexp_replace(phone, '\D', '', 'g') = '01064141983';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '1201916018';
update public.profiles set pickup_stop = 'خليل حمادة' where regexp_replace(phone, '\D', '', 'g') = '01065499087';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01282876048';
update public.profiles set pickup_stop = 'اخر ابيس' where regexp_replace(phone, '\D', '', 'g') = '01112235169';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '0120481';
update public.profiles set pickup_stop = 'اطلس' where regexp_replace(phone, '\D', '', 'g') = '01553381410';
update public.profiles set pickup_stop = 'اشارة كارفور' where regexp_replace(phone, '\D', '', 'g') = '01283610644';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01055804844';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01275808044';
update public.profiles set pickup_stop = 'المعموره ش٢٥' where regexp_replace(phone, '\D', '', 'g') = '01208595127';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01553750128';
update public.profiles set pickup_stop = 'المنتزة' where regexp_replace(phone, '\D', '', 'g') = '01225679825';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01223080245';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01224358150';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01016776874';
update public.profiles set pickup_stop = 'حديد وصلب' where regexp_replace(phone, '\D', '', 'g') = '01208094446';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01010393126';
update public.profiles set pickup_stop = 'حديد وصلب' where regexp_replace(phone, '\D', '', 'g') = '01205580001';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01279527011';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01101890653';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01022033378';
update public.profiles set pickup_stop = 'كامب شيزار' where regexp_replace(phone, '\D', '', 'g') = '01118847064';
update public.profiles set pickup_stop = 'القسم' where regexp_replace(phone, '\D', '', 'g') = '01551217774';
update public.profiles set pickup_stop = 'القسم' where regexp_replace(phone, '\D', '', 'g') = '01099200104';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01115267719';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01210168246';
update public.profiles set pickup_stop = 'الشرطة العسكرية' where regexp_replace(phone, '\D', '', 'g') = '01031776838';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01273206548';
update public.profiles set pickup_stop = 'خورشيد' where regexp_replace(phone, '\D', '', 'g') = '01228288525';
update public.profiles set pickup_stop = 'الشرطة العسكرية' where regexp_replace(phone, '\D', '', 'g') = '01501499049';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01200098742';
update public.profiles set pickup_stop = 'سان ستيفانو' where regexp_replace(phone, '\D', '', 'g') = '01150242874';
update public.profiles set pickup_stop = 'سان ستيفانو' where regexp_replace(phone, '\D', '', 'g') = '01223397700';
update public.profiles set pickup_stop = 'سيدي بشر' where regexp_replace(phone, '\D', '', 'g') = '01094139927';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01202764040';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01062927729';
update public.profiles set pickup_stop = 'كامب شيزار' where regexp_replace(phone, '\D', '', 'g') = '01200480974';
update public.profiles set pickup_stop = 'المحروسة' where regexp_replace(phone, '\D', '', 'g') = '01158749022';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01201044597';
update public.profiles set pickup_stop = 'اخر سور نادي سبورتنج' where regexp_replace(phone, '\D', '', 'g') = '01201389691';
update public.profiles set pickup_stop = 'شارع الحدايق' where regexp_replace(phone, '\D', '', 'g') = '01066857697';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01004585602';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01211183119';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01200456057';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01229656803';
update public.profiles set pickup_stop = 'المنتزة' where regexp_replace(phone, '\D', '', 'g') = '01010048925';
update public.profiles set pickup_stop = 'ساحل' where regexp_replace(phone, '\D', '', 'g') = '1003611359';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01202900388';
update public.profiles set pickup_stop = 'المنتزة' where regexp_replace(phone, '\D', '', 'g') = '01221388381';
update public.profiles set pickup_stop = 'اخر سور نادي سبورتنج' where regexp_replace(phone, '\D', '', 'g') = '01210196367';
update public.profiles set pickup_stop = 'فضة' where regexp_replace(phone, '\D', '', 'g') = '01282737550';
update public.profiles set pickup_stop = 'ابو يوسف' where regexp_replace(phone, '\D', '', 'g') = '01206256931';
update public.profiles set pickup_stop = 'ابو يوسف' where regexp_replace(phone, '\D', '', 'g') = '01271922113';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01026783039';
update public.profiles set pickup_stop = 'ليزابيلا' where regexp_replace(phone, '\D', '', 'g') = '01208481012';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01225683464';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01211156686';
update public.profiles set pickup_stop = 'نفق ٤٥' where regexp_replace(phone, '\D', '', 'g') = '01283289351';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01212527727';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01287018702';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01098056682';
update public.profiles set pickup_stop = 'المعموره ش٢٥' where regexp_replace(phone, '\D', '', 'g') = '01157699661';
update public.profiles set pickup_stop = 'المعموره ش٢٥' where regexp_replace(phone, '\D', '', 'g') = '01157699166';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01011447794';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01211521920';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01299966749';
update public.profiles set pickup_stop = 'بيتزا دادي' where regexp_replace(phone, '\D', '', 'g') = '01278432674';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01200650430';
update public.profiles set pickup_stop = 'المندرة' where regexp_replace(phone, '\D', '', 'g') = '01029536633';
update public.profiles set pickup_stop = 'شعراوي' where regexp_replace(phone, '\D', '', 'g') = '01157806048';
update public.profiles set pickup_stop = 'جامع يحيى' where regexp_replace(phone, '\D', '', 'g') = '01060209404';
update public.profiles set pickup_stop = 'البيضة' where regexp_replace(phone, '\D', '', 'g') = '01212881998';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01550811866';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01043844539';
update public.profiles set pickup_stop = 'الشيراتون' where regexp_replace(phone, '\D', '', 'g') = '01104795798';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '1202268894';
update public.profiles set pickup_stop = 'بيتزا دادي' where regexp_replace(phone, '\D', '', 'g') = '01284333282';
update public.profiles set pickup_stop = 'سانتوس' where regexp_replace(phone, '\D', '', 'g') = '01015972926';
update public.profiles set pickup_stop = 'بلازا' where regexp_replace(phone, '\D', '', 'g') = '01033158822';
update public.profiles set pickup_stop = 'واصلة المعمورة' where regexp_replace(phone, '\D', '', 'g') = '01029216169';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01016292410';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01551773185';
update public.profiles set pickup_stop = 'كومباوند الفيروزة' where regexp_replace(phone, '\D', '', 'g') = '01010587655';
update public.profiles set pickup_stop = 'المدهش' where regexp_replace(phone, '\D', '', 'g') = '01556980327';
update public.profiles set pickup_stop = 'كارفور القهوة' where regexp_replace(phone, '\D', '', 'g') = '01227123595';
update public.profiles set pickup_stop = 'كومباوند الفيروزة' where regexp_replace(phone, '\D', '', 'g') = '01024860960';
update public.profiles set pickup_stop = 'العماروة' where regexp_replace(phone, '\D', '', 'g') = '01025422690';
update public.profiles set pickup_stop = 'اشارة هندسة' where regexp_replace(phone, '\D', '', 'g') = '01278930338';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01287962792';
update public.profiles set pickup_stop = 'الشمس المشرقة' where regexp_replace(phone, '\D', '', 'g') = '01272299636';
update public.profiles set pickup_stop = 'جامع يحيى' where regexp_replace(phone, '\D', '', 'g') = '01024711579';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01007498217';
update public.profiles set pickup_stop = 'المعموره ش٢٥' where regexp_replace(phone, '\D', '', 'g') = '01283001596';
update public.profiles set pickup_stop = 'المحروسة' where regexp_replace(phone, '\D', '', 'g') = '01281305914';
update public.profiles set pickup_stop = 'بنزينة قسم الرمل' where regexp_replace(phone, '\D', '', 'g') = '01212699308';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01275674260';
update public.profiles set pickup_stop = 'وي الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01200598662';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01211188712';
update public.profiles set pickup_stop = 'المنتزة' where regexp_replace(phone, '\D', '', 'g') = '01158780279';
update public.profiles set pickup_stop = 'صيدلية خليل' where regexp_replace(phone, '\D', '', 'g') = '01220056721';
update public.profiles set pickup_stop = 'ابو يوسف' where regexp_replace(phone, '\D', '', 'g') = '01204702274';
update public.profiles set pickup_stop = 'بنزينة قسم الرمل' where regexp_replace(phone, '\D', '', 'g') = '01550777213';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01212330023';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01090594860';
update public.profiles set pickup_stop = 'الشاطبي' where regexp_replace(phone, '\D', '', 'g') = '01281485206';
update public.profiles set pickup_stop = 'الاكاديمية' where regexp_replace(phone, '\D', '', 'g') = '01037093265';
update public.profiles set pickup_stop = 'كرم الشام' where regexp_replace(phone, '\D', '', 'g') = '01067993737';
update public.profiles set pickup_stop = 'شارع سيف' where regexp_replace(phone, '\D', '', 'g') = '01287632971';
update public.profiles set pickup_stop = 'دوران جيهان' where regexp_replace(phone, '\D', '', 'g') = '01284085619';
update public.profiles set pickup_stop = 'الدوران' where regexp_replace(phone, '\D', '', 'g') = '01127707914';
update public.profiles set pickup_stop = 'البيضة' where regexp_replace(phone, '\D', '', 'g') = '01201376518';
update public.profiles set pickup_stop = 'بيتزا دادي' where regexp_replace(phone, '\D', '', 'g') = '01092374068';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01204406507';
update public.profiles set pickup_stop = 'دوران فيكتور عمانويل' where regexp_replace(phone, '\D', '', 'g') = '01271438668';
update public.profiles set pickup_stop = 'خليل حمادة' where regexp_replace(phone, '\D', '', 'g') = '01100156664';
update public.profiles set pickup_stop = 'اشارة كارفور' where regexp_replace(phone, '\D', '', 'g') = '01001243511';
update public.profiles set pickup_stop = 'الهانوفيل' where regexp_replace(phone, '\D', '', 'g') = '01010701265';
update public.profiles set pickup_stop = 'شعراوي' where regexp_replace(phone, '\D', '', 'g') = '01222639260';
update public.profiles set pickup_stop = 'شعراوي' where regexp_replace(phone, '\D', '', 'g') = '01270167382';
update public.profiles set pickup_stop = 'الديب مول' where regexp_replace(phone, '\D', '', 'g') = '01206270889';
update public.profiles set pickup_stop = 'كوبري 21' where regexp_replace(phone, '\D', '', 'g') = '01554219514';
update public.profiles set pickup_stop = 'المحروسة' where regexp_replace(phone, '\D', '', 'g') = '01092628520';
update public.profiles set pickup_stop = 'محمد نجيب' where regexp_replace(phone, '\D', '', 'g') = '01221353148';
update public.profiles set pickup_stop = 'كوبري الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01206369639';
update public.profiles set pickup_stop = 'سانتوس' where regexp_replace(phone, '\D', '', 'g') = '01222531267';
update public.profiles set pickup_stop = 'كارفور القهوة' where regexp_replace(phone, '\D', '', 'g') = '01111594465';
update public.profiles set pickup_stop = 'محرم بك' where regexp_replace(phone, '\D', '', 'g') = '01035737576';
update public.profiles set pickup_stop = 'بنزينة السلام' where regexp_replace(phone, '\D', '', 'g') = '01279981438';
update public.profiles set pickup_stop = 'كابو' where regexp_replace(phone, '\D', '', 'g') = '01200958752';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01116435776';
update public.profiles set pickup_stop = 'بنزينة قسم الرمل' where regexp_replace(phone, '\D', '', 'g') = '1204677562';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01282834063';
update public.profiles set pickup_stop = 'بنزينة جليم' where regexp_replace(phone, '\D', '', 'g') = '01275175827';
update public.profiles set pickup_stop = 'المعموره ش٢٥' where regexp_replace(phone, '\D', '', 'g') = '01002394967';
update public.profiles set pickup_stop = 'شارع مرتضى' where regexp_replace(phone, '\D', '', 'g') = '01149278559';
update public.profiles set pickup_stop = 'بيتزا دادي' where regexp_replace(phone, '\D', '', 'g') = '01221259204';
update public.profiles set pickup_stop = 'كيلوبترا' where regexp_replace(phone, '\D', '', 'g') = '01203150015';
update public.profiles set pickup_stop = 'فيكتوريا' where regexp_replace(phone, '\D', '', 'g') = '01274068771';
update public.profiles set pickup_stop = 'خورشيد' where regexp_replace(phone, '\D', '', 'g') = '01212244064';
update public.profiles set pickup_stop = 'كيلوبترا' where regexp_replace(phone, '\D', '', 'g') = '01030409664';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '01224997347';
update public.profiles set pickup_stop = 'القسم' where regexp_replace(phone, '\D', '', 'g') = '01224210482';
update public.profiles set pickup_stop = 'كنيسة جناكليس' where regexp_replace(phone, '\D', '', 'g') = '01277362013';
update public.profiles set pickup_stop = 'نقطة الابراهيمية' where regexp_replace(phone, '\D', '', 'g') = '011157836590';
update public.profiles set pickup_stop = 'بنزينة جليم' where regexp_replace(phone, '\D', '', 'g') = '01094150324';
update public.profiles set pickup_stop = 'الشاطبي' where regexp_replace(phone, '\D', '', 'g') = '01200947815';
update public.profiles set pickup_stop = 'كرموز' where regexp_replace(phone, '\D', '', 'g') = '01202056420';
update public.profiles set pickup_stop = 'باب شرق' where regexp_replace(phone, '\D', '', 'g') = '01090970996';
update public.profiles set pickup_stop = 'البيطاش' where regexp_replace(phone, '\D', '', 'g') = '01210749992';
